export const ProductsData = [
  {
    id: '4f0d2cdc3aaf43fc912a81f13a333b74',
    title: 'VERSACE HEAVY CHAIN NECKLACE',
    brand: 'VERSACE',
    color: 'BROWN',
    price: '199',
    categories: [
      'Brands',
      'Brands / VERSACE',
      'Clothing',
      'Clothing / Sweats',
      'VIP Sale',
    ],
    department: 'Sweats',
    gender: 'Mens',
    image_one:
      'https://media.endclothing.com/media/f_auto,q_auto:eco/prodmedia/media/catalog/product/2/9/29-07-20_DG16949-DJMT-KOT_m1_1.jpg',
    image_two:
      'https://media.endclothing.com/media/f_auto,q_auto:eco/prodmedia/media/catalog/product/2/9/29-07-20_DG16949-DJMT-KOT_3_1.jpg',
    stock: '11',
    availableSizes: ['xs', 's', 'm'],
  },
  {
    id: 'ef206a6ca0804189bef9641a01f9c133',
    title: 'NIKE AIR FORCE 1 SHADOW W',
    brand: 'NIKE',
    color: 'BROWN',
    price: '99',
    categories: [
      'Brands',
      'Brands / NIKE',
      'Clothing',
      'Clothing / Sweats',
      'VIP Sale',
    ],
    department: 'Sweats',
    gender: 'Mens',
    image_one:
      'https://media.endclothing.com/media/f_auto,q_auto:eco/prodmedia/media/catalog/product/3/0/30-12-2020_TH_CU8591-001_m1_1.jpg',
    image_two:
      'https://media.endclothing.com/media/f_auto,q_auto:eco/prodmedia/media/catalog/product/3/0/30-12-2020_TH_CU8591-001_4_1.jpg',
    stock: '11',
    availableSizes: ['xs', 's', 'm'],
  },
  {
    id: 'dd10996f626348fc9aa55b3ef40b5ab7',
    title: 'ACNE STUDIOS PANSY GD FACE BEANIE',
    brand: 'ACNE STUDIOS',
    color: 'BROWN',
    price: '399',
    categories: [
      'Brands',
      'Brands / ACNE STUDIOS',
      'Clothing',
      'Clothing / Sweats',
      'VIP Sale',
    ],
    department: 'Sweats',
    gender: 'Mens',
    image_one:
      'https://media.endclothing.com/media/f_auto,q_auto:eco/prodmedia/media/catalog/product/1/6/16-12-2020_JA_C40140-AQR_m1_1.jpg',
    image_two:
      'https://media.endclothing.com/media/f_auto,q_auto:eco/prodmedia/media/catalog/product/1/6/16-12-2020_JA_C40140-AQR_2_1.jpg',
    stock: '11',
    availableSizes: ['xs', 's', 'm'],
  },
  {
    id: '2293d0f3074e47d3bc484a03ed4f339d',
    title: 'MAHARISHI MILTYPE SPORTS SOCK - 3 PACK',
    brand: 'MAHARISHI',
    color: 'BROWN',
    price: '199',
    categories: [
      'Brands',
      'Brands / MAHARISHI',
      'Clothing',
      'Clothing / Sweats',
      'VIP Sale',
    ],
    department: 'Sweats',
    gender: 'Mens',
    image_one:
      'https://media.endclothing.com/media/f_auto,q_auto:eco/prodmedia/media/catalog/product/1/7/17-12-2020_BB_9273-WBO_m1_1.jpg',
    image_two:
      'https://media.endclothing.com/media/f_auto,q_auto:eco/prodmedia/media/catalog/product/1/7/17-12-2020_BB_9273-WBO_2_1.jpg',
    stock: '11',
    availableSizes: ['xs', 's', 'm'],
  },
  {
    id: 'fe76474cdac443fe85b934657d5b26da',
    title: 'WTAPS BEANIE 02',
    brand: 'WTAPS',
    color: 'BROWN',
    price: '19',
    categories: [
      'Brands',
      'Brands / WTAPS',
      'Clothing',
      'Clothing / Sweats',
      'VIP Sale',
    ],
    department: 'Sweats',
    gender: 'Mens',
    image_one:
      'https://media.endclothing.com/media/f_auto,q_auto:eco/prodmedia/media/catalog/product/1/6/16-12-2020_RL_202MADT-HT02-BG_m1_1.jpg',
    image_two:
      'https://media.endclothing.com/media/f_auto,q_auto:eco/prodmedia/media/catalog/product/1/6/16-12-2020_RL_202MADT-HT02-BG_2_1.jpg',
    stock: '11',
    availableSizes: ['ONE SIZE'],
  },
  {
    id: '8c36ba86bd514620bdc0992ebbe36b98',
    title: 'Fucking Awesome Stacked Track Pant',
    brand: 'Fucking Awesome',
    color: 'BROWN',
    price: '199',
    categories: [
      'Brands',
      'Brands / 1017 ALYX 9SM',
      'Clothing',
      'Clothing / Sweats',
      'VIP Sale',
    ],
    department: 'Sweats',
    gender: 'Mens',
    image_one:
      'https://media.endclothing.com/media/f_auto,q_auto:eco,w_400,h_400/prodmedia/media/catalog/product/0/8/08-12-2020_six_aamsw0085fa01-blk_m9.jpg',
    image_two:
      'https://media.endclothing.com/media/f_auto,q_auto:eco,w_400,h_400/prodmedia/media/catalog/product/0/8/08-12-2020_GH_AVUTS0216FA01-WTH_m6_1.jpg',
    stock: '11',
    availableSizes: ['xs', 's', 'm'],
  },
  {
    id: 'a9bebafa2fae47feb42a81c2466f86a5',
    title: 'NIKE RPM WAISTPACK',
    brand: 'NIKE',
    color: 'BLACK',
    price: '29',
    categories: [
      'Brands',
      'Brands / NIKE',
      'Clothing',
      'Clothing / Sweats',
      'VIP Sale',
    ],
    department: 'Sweats',
    gender: 'Mens',
    image_one:
      'https://media.endclothing.com/media/f_auto,q_auto:eco/prodmedia/media/catalog/product/1/8/18-12-2020_aj_cq3817-355_m1.jpg',
    image_two:
      'https://media.endclothing.com/media/f_auto,q_auto:eco/prodmedia/media/catalog/product/1/8/18-12-2020_aj_cq3817-355_3.jpg',
    stock: '11',
    availableSizes: ['xs', 's', 'm'],
  },
  {
    id: '5faf83c5acf84b4ab4726d8613a655dd',
    title: 'NEIGHBORHOOD X MOTORHEAD TEE',
    brand: 'NEIGHBORHOOD',
    color: 'BLACK',
    price: '69',
    categories: [
      'Brands',
      'Brands / NEIGHBORHOOD',
      'Clothing',
      'Clothing / Sweats',
      'VIP Sale',
    ],
    department: 'Sweats',
    gender: 'Mens',
    image_one:
      'https://media.endclothing.com/media/f_auto,q_auto:eco/prodmedia/media/catalog/product/3/0/30-12-2020_TH_202PCMHN-ST02S-BLK_1_1.jpg',
    image_two:
      'https://media.endclothing.com/media/f_auto,q_auto:eco/prodmedia/media/catalog/product/3/0/30-12-2020_TH_202PCMHN-ST02S-BLK_5_1.jpg',
    stock: '11',
    availableSizes: ['s', 'l', 'xxl'],
  },
  {
    id: '5faf83c5acf34b4ab4723d8613a655dd',
    title: 'MAHARISHI KIMONO CHORE JACKET',
    brand: 'MAHARISHI',
    color: 'MAHA OLIVE',
    price: '239',
    categories: [
      'Brands',
      'Brands / MAHARISHI',
      'Clothing',
      'Clothing / Sweats',
      'VIP Sale',
    ],
    department: 'Sweats',
    gender: 'Mens',
    image_one:
      'https://media.endclothing.com/media/f_auto,q_auto:eco/prodmedia/media/catalog/product/0/4/04-11-2020_MO_6375-MO_1_1.jpg',
    image_two:
      'https://media.endclothing.com/media/f_auto,q_auto:eco/prodmedia/media/catalog/product/0/4/04-11-2020_MO_6375-MO_5_1.jpg',
    stock: '11',
    availableSizes: ['m', 'l', 'xxl'],
  },
];

export const brandData = [
  { name: 'adidas Consortium' },
  { name: 'adidas Originals' },
  { name: 'adidas Performance' },
  { name: 'Arcteryx' },
  { name: 'ASICS' },
  { name: 'Canada Goose' },
  { name: 'Carhartt WIP' },
  { name: 'Comme des Garcons' },
  { name: 'Hoka One One' },
  { name: 'Jordan' },
  { name: 'Maharishi' },
  { name: 'Nike' },
  { name: 'Nike SB' },
  { name: 'Patagonia' },
  { name: 'Stone Island' },
  { name: 'Stone Island Shadow Project' },
];
